[package]
name = "y2024"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
regex = "1.10.6"
itertools = "0.13.0"
rayon = "1.10.0"
ndarray = "0.15.2"
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
