[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
itertools = "0.13.0"
md-5 = "0.10.6"
rayon = "1.10.0"
regex = "1.10.6"
strum = "0.26.3"
strum_macros = "0.26.4"
