[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
md-5 = "0.10.6"
ndarray = "0.15.2"
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
regex = "1.10.6"
strum = "0.26.3"
strum_macros = "0.26.4"
